#!/bin/bash
#
source $(git root)/_

# ln -sf ../nzt-conf.js $DIST/javascripts/_conf.js

rsync -OPrv --copy-links $DIST/ \
      $SRV_USER@$SRV_SERVER:$SRV_DEST \
      --delete-after

# In case deploying the entire project (not only $DIST):
#
# --exclude=_
# --exclude=.git
# --exclude=run

# ln -sf ../localhost-conf.js $DIST/javascripts/_conf.js
