#!/bin/bash

cat <<EOF
NPM init
========
EOF
echo -e ""

npm init


cat <<EOF

=======================================================================
Added commented scripts to package.json you should fix it before doing:
=======================================================================

EOF

cat <<EOF
NPM install
===========

$ npm install bower coffee-script gulp gulp-coffee gulp-sourcemaps gulp-uglify gulp-util --save --loglevel=silent

EOF

cat >> package.json <<'EOF'
  // "scripts": {
  //   "gulp": "./node_modules/gulp/bin/gulp.js",
  //   "bower": "./node_modules/bower/bin/bower"
  // }
EOF

cat <<EOF
Bower dependencies
==================

$ npm run bower install --save jquery d3 bootstrap git://github.com/svexican/js-extras git://github.com/svexican/web-extras

EOF
